myprint/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  ##============================================================##
  ## API
  ##============================================================##
  namespace :api, defaults: {format: 'json'} do
    namespace :v2 do

      ##============================================================##
      ## Orders
      ##============================================================##
      match "orders/:id"    => 'orders#show',           :via => :get
      ##============================================================##
      ## Templates
      ##============================================================##
      match "templates/(:type_id)"    => 'templates#index',        :via => :get
      match "templates/:id/pdfs"    => 'templates#get_pdfs',     :via => :get

    end
  end


  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}


  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do
    ##============================================================##
    ## Devise
    ##============================================================##
    devise_for :users, skip: :omniauth_callbacks

    ##============================================================##
    ## Dashboard
    ##============================================================##
    root to: "pages#home"
    match "dashboard"       => "dashboard#index",           :via => [:get], :as => :dashboard
    match 'showcase'        => 'dashboard#showcase',        :via => [:get], :as => :dashboard_showcase
    match 'history'         => "dashboard#history",         :via => :get,   :as => :dashboard_history


    authenticate :user, lambda { |u| u.check_role? } do
      mount Sidekiq::Web => '/sidekiq'
    end




    scope "app" do
      match 'preview'         => 'previews#show',                 :via => [:get],   :as => "app_preview"
      match 'preview/g/:id'   => 'previews#generate',             :via => [:post],  :as => "app_preview_generate", :format => :json
      match 'download/:id'    => 'previews#download_preview_pdf', :via => [:get],   :as => "app_preview_download"
      match 'preview/error'   => 'previews#error',                :via => [:get],   :as => "app_preview_error"
    end



    ##============================================================##
    ## Admin
    ##============================================================##
    scope "admin" do
      ##============================================================##
      ## admin
      ##============================================================##
      ##============================================================##
      ## Print Template
      ##============================================================##
      match 'print-templates'                   => 'print_templates#print_templates',               via: [:get],    :as => "admin_print_templates"
      match 'print-templates/new'               => 'print_templates#print_templates_new',           via: [:get],    :as => "admin_print_templates_new"
      match 'print-templates/:id'               => 'print_templates#print_templates_edit',          via: [:get],    :as => "admin_print_templates_edit"
      match 'print-templates/:id'               => 'print_templates#print_templates_update',        via: [:patch],  :as => "admin_print_templates_update"
      match 'print-templates/:id'               => 'print_templates#print_templates_delete',        via: [:delete], :as => "admin_print_templates_delete"
      ##============================================================##
      ## Print Template Pdfs
      ##============================================================##
      match 'print-templates/pdfs/:id'              => 'print_templates#print_templates_pdf_edit',        via: [:get],        :as => 'admin_print_template_pdf_edit'
      match 'print-templates/pdfs/:id/dictionary'   => 'print_templates#print_templates_pdf_dictionary',  via: [:get],        :as => 'admin_print_template_pdf_dictionary'
      match 'print-templates/pdfs/:id/deactivate'   => 'print_templates#print_templates_pdf_deactivate',  via: [:post],       :as => 'admin_print_template_pdf_deactivate'
      match 'print-templates/pdfs/:id/reactivate'   => 'print_templates#print_templates_pdf_reactivate',  via: [:post],       :as => 'admin_print_template_pdf_reactivate'
      match 'print-templates/pdfs/:id'              => 'print_templates#print_templates_pdf_update',      via: [:patch],      :as => 'admin_print_template_pdf_update'
      resources :fonts
      resources :print_template_sizes
    end



  end
end

myprint/app/views/previews/error.html.erb
<div class="container">
  <div class="a-left mt20"><%= @error %></div>
</div>

myprint/app/views/previews/show.html.erb
<% @title_for_layout       = "#{@order.id}" %>
<%= render 'layouts/partials/generic_meta' %>

<% page_width  = @dictionary[:document][:page_width] %>
<% page_height = @dictionary[:document][:page_height] %>

<%= content_for :head do %>
<script src="https://js.pusher.com/3.0/pusher.min.js"></script>
<% end %>


<div id="appView">
  <%# Left %>
  <div id="leftSide" class="bg-dark-grey">
    <div id="pictureContainer">
      <% @pictures.sort{|p1,p2| p1[:uid] <=> p2[:uid]}.group_by{|p| p[:property]}.each do |property_id, picture_group| %>
      <div class="color-white a-left"><%= "Propriété ##{picture_group.first[:uid]} (#{property_id})" %></div>
      <ul class="list-inline center">
        <% picture_group.each do |p| %>
        <li style="max-width:120px;" class="draggable mt5 relative pl0 pr0" data-check="check_image_<%= p[:uid] %>" data-image="<%= p[:pictures][:large] %>" data-x="<%= p[:x] %>" data-y="<%= p[:y] %>">
          <span id="check_image_<%= p[:uid] %>" class="check_images" style="display: none;"><i class="fa fa-lg fa-check-circle color-green" aria-hidden="true"></i></span>
          <%= image_tag p[:pictures][:large], :class=>"img-responsive" %>
        </li>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>

  <%# Right %>
  <div id="rightSide">
    <div class="f-right mt3 mr10">
      <%= link_to t('app.cancel'), params[:redirect_uri], :class=>"btn btn-default" if params[:redirect_uri].present? %>
      <a id="startGeneration" data-action="<%= app_preview_generate_url(@order.id,:format=>"json") %>" class="btn btn-primary pl20 pr20"><%= t('print.preview') %></a>
    </div>
    <ul class="nav nav-tabs" role="tablist">
      <% (1..(@dictionary[:document][:page_count].to_i)).each do |page| %>
      <li role="presentation" class="<%= page == 1 ? "active" : nil %>">
        <a href="#panel_<%= page %>" aria-controls="panel_<%= page %>" role="tab" data-toggle="tab" class="tab-link">
          <%= t("print.#{@dictionary[:document][:page_count] == 2 ? 'recto_verso' : 'page'}_c", :count => page) %>
        </a>
      </li>
      <% end %>
    </ul>
    <div class="tab-content">
      <% (1..(@dictionary[:document][:page_count].to_i)).each do |page| %>
      <div role="tabpanel" class="mt10 mb20 tab-pane <%= page == 1 ? "active" : nil %>" id="panel_<%= page %>">
        <div class="container-fluid pt10 pb20">
          <div class="row">
            <div class="col-xs-10 col-xs-offset-1 mt10 mb10" id="<%= "page#{page}" %>">
              <section class="relative">
                <div class="h6 z-index-1000 pt3 pb3 pl5 pr5 absolute absolute-top-right bg-black color-white">
                  <%= t("print.#{@dictionary[:document][:page_count] == 2 ? 'recto_verso' : 'page'}_c", :count => page) %>
                </div>
                <div class="absolute bg-cover" style='width:100%; height:100%; border:1px solid grey; background-image: url("<%= @pdf.model.url.sub('model.pdf', page.to_s+'.png') %>")'>
                  <% @dictionary[:blocks].select{|b| b[:page] == page && (b[:type] == "image" || b[:type] == "text")}.each do |block| %>

                  <% pos = block[:position] %>
                  <% b_left   = (pos[:left].to_f/page_width.to_f*100.00)%>
                  <% b_top    = (pos[:top].to_f/page_height.to_f*100.00)%>
                  <% b_width  = (pos[:width].to_f/page_width.to_f*100.00)%>
                  <% b_height = (pos[:height].to_f/page_height.to_f*100.00)%>

                  <% if block[:type] == "image" && block[:editable] == "true" %>
                  <div class="delete_image" data-check="" data-name="<%= block[:name] %>" style="<%= "display: none; left:calc(#{b_left}% + 5px); top:calc(#{b_top}% + 5px);" %>"><i class="fa fa-lg fa-trash color-black" aria-hidden="true"></i></div>
                  <% end %>

                  <% opacity = block[:properties].select{|prop| prop[:name] == "p9:opacity"}.first %>
                  <% layer = block[:properties].select{|prop| prop[:name] == "p9:layer"}.first %>
                  <% my_style = "#{block[:type] == "image" && block[:url].present? && block[:editable] == "true" ? "background-image: url('#{block[:url]}');" : nil} #{block[:type] == "image" && block[:editable] == "true" ? (opacity.present? ? "opacity: #{opacity[:value]};" : "opacity: 1;") : nil} #{block[:type] == "image" && block[:editable] == "true" && b_width > 95 && b_height > 95 ? "z-index: 10;" : "z-index: 100;"} width:#{b_width}%; left:#{b_left}%; top:#{b_top}%; height:#{b_height}%; z-index: #{layer.present? ? 100+layer[:value].to_i : 100};" %>
                  <% my_class = "#{block[:type] == "image" && block[:editable] == "true" ? "dropzone" : nil} #{block[:type] == "text" ? (block[:editable] == "true" ? "bg-editable" : "bg-noneditable") : nil}" %>

                  <div data-name="<%= block[:name] %>" class="<%= my_class %> absolute bg-cover" style="<%= my_style %>">
                    <% if block[:description].present? && (block[:type] == "text" || block[:editable] == "false") %>
                    <div class="h6 z-index-1000 absolute absolute-top-right <%= block[:editable] == "true" ? "bg-black color-white" : "bg-lightgrey color-black border-black" %> <%= b_height < 5 ? "fs#{b_height.to_i * 3} pt2 pb2 pl2 pr2" : "pt3 pb3 pl5 pr5" %>">
                      <%= block[:description] %>
                    </div>
                    <% end %>

                    <% if block[:type] == "image" && block[:editable] == "true" %>
                    <div class="center bold h5 dropzone-layer" style="display:table-cell;vertical-align:middle;"><%= t('print.step_1_iframe_help') %></div>
                    <% end %>
                  </div>

                  <% end %>
                </div>
                <div class="svgContainer" style="padding-bottom:<%= (page_height.to_f/page_width.to_f*100.00) %>%">
                  <svg viewBox="<%= "0 0 #{page_width} #{page_height}" %>"></svg>
                </div>
              </section>
              <section class="mt20">
                <% if (@textlines.present? && @textlines[page].present?) || (@textflows.present? && @textflows[page].present?) %>
                <div class="color-white bold">
                  <span class="bg-black pt3 pb3 pl5 pr5">
                    <%= t('print.informations') %>
                  </span>
                </div>
                <% end %>

                <% if @textlines.present? && @textlines[page].present? %>
                <table class="table table-condensed table-no-bordered table-valign-middle">
                  <% @textlines[page].each do |textline| %>
                  <tr>
                    <td class="a-right" style="width:30%"><label class="color-grey mt5"> <%= textline[:description].present? ? textline[:description] : textline[:name] %></label></td>
                    <td class="a-left">
                      <% max_char = textline[:properties].select{|prop| prop[:name] == "p9:max_char"}.first %>
                      <input class="form-control <%= max_char.present? ? 'charCount' : nil %>" value="<%= textline[:content] %>" data-maxChar="<%= max_char.present? ? max_char[:value] : nil %>" data-page="<%= textline[:page] %>" data-name="<%= textline[:name] %>" type="text">
                      <% if max_char.present? %>
                      <p><span class="textLimit" data-name="<%= textflow[:name] %>"></span> <%= t('app.remaining_characters') %></p>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                  <% end %>
                </table>

                <% if @textflows.present? && @textflows[page].present? %>
                <% @textflows[page].each do |textflow| %>
                <% line_count = textflow[:name].include?('with_newline') ? textflow[:name].split('_and_').size : 0 %>
                <div class="mt10">
                  <label>
                    <span class="color-primary"><%= textflow[:description].present? ? textflow[:description] : textflow[:name] %></span>
                    <span><%= line_count > 1 ? "(#{line_count} #{t('app.lines')})" : nil %></span>
                    <span data-name="<%= textflow[:name] %>" data-reset="<%= textflow[:content] %>" class="pointer mt5 color-black ml5 fs11 textPrintDescriptionReset"><%= t('print.reset') %></span>
                  </label>
                  <% max_char = textflow[:properties].select{|prop| prop[:name] == "p9:max_char"}.first %>
                  <textarea class="form-control textarea-noresize <%= max_char.present? ? 'charCount' : nil %>" data-maxChar="<%= max_char.present? ? max_char[:value] : nil %>" data-page="<%= textflow[:page] %>" data-name="<%= textflow[:name] %>"><%= textflow[:content] %></textarea>
                  <% if max_char.present? %>
                  <p><span class="textLimit" data-name="<%= textflow[:name] %>"></span> <%= t('app.remaining_characters') %></p>
                  <% end %>
                </div>
                <% end %>
                <% end %>
              </section>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>



<div id="appViewResult" style="display: none;">
  <div class="bg-dark-grey">
    <div class="container center">
      <div id="stepName" class="h4 color-white mt20 mb20"></div>
    </div>
  </div>
  <div class="container center">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div id="owl-slider" class="owl-carousel owl-theme mt20" style="display:none;">
          <% (1..@dictionary[:document][:page_count].to_i).each do |row_i| %>
          <div id="<%= "magazine_page_#{row_i}" %>" class="item">
            <%= image_tag "http://placehold.it/#{@dictionary[:document][:page_width]}x#{@dictionary[:document][:page_height]}?text=page-#{row_i}", :class=>"img-responsive" %>
          </div>
          <% end %>
        </div>
        <div class="mt40 center" id="appViewResultActions" style="display: none;">
          <% if @print_template.print_template_type.slug == "showcase" %>
          <%= link_to t('app.download'), app_preview_download_path(@order.id), :class=> "btn btn-primary ml10 mr10", :id => "download_pdf", :target => "_blank" %>
          <% else %>
          <%= link_to(t('app.download'), app_preview_download_path(@order.id), :class=> "btn btn-primary ml10 mr10", :id => "download_pdf", :target => "_blank") if params[:debug] == "1" %>
          <%= link_to t('app.validate_preview'), "#", :class=> "btn btn-primary ml10 mr10", :id => "backtostore", :data =>{:confirm => t("print.confirm")} %>
          <% end %>
          <a id="backToStep1" class="btn btn-default ml10 mr10"><%= t('app.modify') %></a>
        </div>
      </div>
    </div>
  </div>
</div>




<%= javascript_tag do %>
window.dictionary     = <%= raw @dictionary.to_json %>

window.pusher_key     = "<%= ENV["pusher_key"] %>"
window.channel        = "<%= @order.channel %>"

window.color_editable = <%= @print_template.color_editable %>
window.color_default  = <%= [@print_template.color_c,@print_template.color_m,@print_template.color_y,@print_template.color_k] %>

window.store_url      = "<%= params[:redirect_uri] %>"
<% end %>