storeimmo/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  ##============================================================##
  ## DoorKeeper
  ##============================================================##
  use_doorkeeper

  ##============================================================##
  ## sidekiq
  ##============================================================##
  mount Sidekiq::Web => '/sidekiq'

  ##============================================================##
  ## API
  ##============================================================##
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      ##============================================================##
      ## oAuth
      ##============================================================##
      match 'me'              => "oauth#me",          :via => :get

      ##============================================================##
      ## Gateways
      ##============================================================##
      match '/gateways/:name'                   => "gateways#show",     :via => :get
      match '/gateways/track/:activation_id'    => "gateways#track",    :via => :post

      ##============================================================##
      ## Properites
      ##============================================================##
      match 'properties'      => "properties#index",  :via => :get
      match 'properties/:id'  => "properties#show",   :via => :get

      ##============================================================##
      ## Services
      ##============================================================##
      match 'services'                        => "services#index",    :via => :get
      match 'services/menu'                   => "services#menu",     :via => :get
      match 'services/debit/:id/:quantity'    => "services#debit",    :via => :post

      ##============================================================##
      ## Cart
      ##============================================================##
      scope 'cart' do
        match 'update_shipping'         => 'checkouts#update_shipping',  :via => :get
      end

      ##============================================================##
      ## Variants
      ##============================================================##
      scope 'variants' do
        match "/new/:variant_category_id"       => "variants#new",         :via => [:get]
        match "/:variant_category_id"           => "variants#delete",      :via => [:delete]
      end
    end
  end

  ##============================================================##
  ## All Apps Routes
  ##============================================================##
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do
    ##============================================================##
    ## Devise
    ##============================================================##
    devise_for :users
    devise_for :clients, :controllers => {
      :sessions       => "clients/sessions",
      :registrations  => "clients/registrations",
      :passwords      => "clients/passwords",
    }


    ##============================================================##
    ## HomePage
    ##============================================================##
    root "pages#home"
    match 'stylesheet'        => 'pages#stylesheet',        :via => [:get],   :format => [:css]
    match 'choose-store'      => 'pages#choose_store',      :via => [:get],   :as => :choose_your_store
    match "product/:id"       => "pages#product_show",      :via => [:get],   :as => :product_show
    match "category/(:id)"    => "pages#category_show",     :via => [:get],   :as => :category_show
    match "contact"           => "pages#contact",           :via => [:get],   :as => :contact
    match "contact"           => "pages#contact_create",    :via => [:post],  :as => :contact_create
    match "faq"               => "pages#faq",               :via => [:get],   :as => :faq
    match "thanks"            => "pages#thanks",            :via => [:get],   :as => :thanks


    ##============================================================##
    ## Team Invitation
    ##============================================================##
    match "invitation"      => "invitations#invitation",          :via => [:get],    :as => :invitation
    match "invitation"      => "invitations#invitation_accept",   :via => [:post],   :as => :invitation_accept

    ##============================================================##
    ## Wysiwyg
    ##============================================================##
    match 'wysiwyg/pictures'        => 'application#wysiwyg_picture_manager',via: [:post] ,:as => 'wysiwyg_picture_manager', :format => "json"
    match 'wysiwyg/pictures/d'      => 'application#wysiwyg_picture_delete',via: [:post] ,:as => 'wysiwyg_picture_delete'

    ##============================================================##
    ## Publipostage
    ##============================================================##
    match 'publipostage'            => "publipostage#find_routes", :via => [:post], :as => "publipostage"

    ##============================================================##
    ## Dashboard
    ##============================================================##
    scope "dashboard" do
      match "flow"                => "dashboard#flow",                :via => [:get],   :as => :dashboard_flow
      ##============================================================##
      ## Authorizations
      ##============================================================##
      match "/"                   => "dashboard#index",               :via => [:get],     :as => :dashboard
      match "plans"               => "dashboard#plans",               :via => [:get],     :as => :dashboard_plans
      match "tokens"              => "dashboard#tokens",              :via => [:get],     :as => :dashboard_tokens
      match "purchases"           => "dashboard#purchases",           :via => [:get],     :as => :dashboard_purchases
      match "olds"                => "dashboard#old_authorizations",  :via => [:get],     :as => :dashboard_old_authorizations
      ##============================================================##
      ##
      ##============================================================##
      match "checkout/edit/:pricing_id"  => "dashboard#checkout_edit",           :via => [:get],     :as => :dashboard_checkout_edit
      match "service/:id/cancel"         => "dashboard#cancel",              :via => [:delete],  :as => :dashboard_cancel
      ##============================================================##
      ## Shareimmo
      ##============================================================##
      match "shareimmo"           => "dashboard#shareimmo_signin",    :via => [:get],   :as => :dashboard_shareimmo
      ##============================================================##
      ## Billing
      ##============================================================##
      match "billing"             => "dashboard#billing",             :via => [:get],   :as => :dashboard_billing
      match "billing/:id"         => "dashboard#billing_view",        :via => [:get],   :as => :dashboard_billing_view
      match "bill/:id"            => "dashboard#redirect_to_bill",    :via => :get,     :as => :dashboard_redirect_to_bill
      match "bill/regenerate/:id" => "dashboard#regenerate_bill",     :via => :get,     :as => :dashboard_regenerate_bill
      ##============================================================##
      ## Team
      ##============================================================##
      match "team"                => "dashboard#team",                   :via => [:get],      :as => :dashboard_team
      match "team-member/new"     => "dashboard#team_member_create",     :via => [:post],     :as => :dashboard_team_member_create
      match "team-member/:id"     => "dashboard#team_member_resend",     :via => [:get],      :as => :dashboard_team_member_resend
      match "team-member/:id"     => "dashboard#team_member_delete",     :via => [:delete],   :as => :dashboard_team_member_delete
      match "team/switch/:id"     => "dashboard#change_my_team",         :via => [:post],     :as => :dashboard_change_my_team
      ##============================================================##
      ## Profile
      ##============================================================##
      match "profile"       => "dashboard#profile",         :via => [:get],     :as => :dashboard_profile
      match "profile/:id"   => "dashboard#profile_update",  :via => [:patch],   :as => :dashboard_profile_update
      ##============================================================##
      ## Credit cards
      ##============================================================##
      match "cards"             => "credit_cards#index",            :via => [:get],    :as => :dashboard_cards
      match "card"              => "credit_cards#card_new",         :via => [:post],   :as => :dashboard_card_new
      match "card/:stripe_id"   => "credit_cards#card_default",     :via => [:post],   :as => :dashboard_card_default
      match "card/:stripe_id"   => "credit_cards#card_delete",      :via => [:delete], :as => :dashboard_card_delete
      ##============================================================##
      ## Gateway
      ##============================================================##
      match "gateway"             => "dashboard#gateway",            :via => [:get],    :as => :dashboard_gateway
      match "gateway"             => "dashboard#gateway_create",     :via => [:post],   :as => :dashboard_gateway_create
      match "gateway/:id"         => "dashboard#gateway_update",     :via => [:patch],  :as => :dashboard_gateway_update
      match "gateway/:id"         => "dashboard#gateway_delete",     :via => [:delete], :as => :dashboard_gateway_delete

storeimmo/app/views/pages/_header_support.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= " #{current == 1 ? 'active' : nil}" %>"><%= link_to t('app.contact'), contact_path %></li>
        <li class="<%= " #{current == 2 ? 'active' : nil}" %>"><%= link_to t('app.faq'), faq_path %></li>
      </ul>
    </div>
  </div>
</nav>

storeimmo/app/views/pages/_newsletter.html.erb
<section id="newsletter-card" class="pAll15 mt30">
  <h2 class="fs16 color-primary bold mb5"><%= t('newsletter.newsletter') %></h2>
  <p class="color-grey fs12 mb10"><%= t('newsletter.tagline') %></p>
  <form action="#">
    <input type="email" placeholder="Votre email" class="fs12">
    <input type="submit" value="GO!" class="pl10 pr10 lh30">
  </form>
  <p class="text-center fs12 color-grey mt15 mb0"><%= t('newsletter.tagline2') %></p>
</section>

storeimmo/app/views/pages/choose_store.html.erb
<div class="container">
  <% @stores.in_groups_of(3,false) do |row_stores| %>
  <div class="row">
    <% row_stores.each do |store| %>
    <div class="col-xs-4">
      <div class="h4 center"><%= store.name %></div>
      <%= link_to "http://#{store.domain}" do  %>
      <div class="well well-sm center" style="<%= "background-color:#{store.color2}" %>">
        <%= image_tag store.logo.url(:medium_transparent), :class=>"img-responsive" %>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

storeimmo/app/views/pages/contact.html.erb
<% @title_for_layout = @brand = t('app.contact') %>
<%= render 'layouts/generic_meta' %>

<%= render 'pages/header_support', :current=> 1 %>

<div class="container colored-sides">
  <div class="left-light-blue-bg"></div>
  <div class="row row-20 same-height-col">
    <section class="col-md-4 bg-light-blue pt25 pb60">
      <h2 class="fs16 medium color-black mb10"><%= t('contact_faq.contact_title') %></h2>
      <p class="color-grey fs14"><%= t('contact_faq.contact_tagline') %></p>
      <section class="mt5 pt10 pb10 pl10 pr10 bg-white br2 border-grey bAll">
        <h3 class="fs14 color-primary normal"><%= @store.name %></h3>
        <p class="fs12 color-grey lh18 mt5 mb5"><%= simple_format(@store.address) %></p>
        <% if @store.contact_email.present? %>
        <div><i class="fa fa-at"></i> : <a href="mailto:<%= @store.contact_email %>" class="color-link"><%= @store.contact_email %></a></div>
        <% end %>
        <% if @store.contact_phone.present? %>
        <div><i class="fa fa-phone"></i> : <a href="tel:<%= @store.contact_phone %>" class="color-link"><%= @store.contact_phone %></a></div>
        <% end %>
      </section>
    </section>
    <section class="col-md-8 pt25 pb60">
      <span class="infobulle inline-block fs12 mb10"><%= t('contact_faq.contact_infobulle').html_safe %></span>
      <%= simple_form_for Contact.new, :url => contact_create_path do |f| %>
      <%= f.input :store_id ,:input_html => {:value => @store.id}, :as => :hidden %>
      <%= f.input :client_id ,:input_html => {:value => current_client.id}, :as => :hidden if client_signed_in? %>
      <div class="row">
        <div class="col-md-6 mb10">
          <h5 class="fs14 medium color-grey mt0 mb5"><%= t('user.first_name') %></h5>
          <%= f.input :first_name, :label => false %>
        </div>
        <div class="col-md-6 mb10">
          <h5 class="fs14 medium color-grey mt0 mb5"><%= t('user.last_name') %></h5>
          <%= f.input :last_name, :label => false %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mb10">
          <h5 class="fs14 medium color-grey mt0 mb5"><%= t('user.email') %></h5>
          <%= f.input :email, :label => false %>
        </div>
        <div class="col-md-6 mb10">
          <h5 class="fs14 medium color-grey mt0 mb5"><%= t('user.phone') %></h5>
          <%= f.input :phone, :label => false %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mb10">
          <h5 class="fs14 medium color-grey mt0 mb10"><%= t('user.company') %></h5>
          <%= f.input :company, :label => false %>
        </div>
      </div>
      <textarea name="" id="" cols="30" rows="8" placeholder="<%= t('contact_faq.type_your_message') %>"></textarea>
      <input type="submit" class="btn btn-primary pt10 pb10 pl25 pr25 pull-right fs16 mt15" value="<%= t('contact_faq.send_message') %>">
      <% end %>
    </section>
  </div>
</div>

storeimmo/app/views/pages/home.html.erb
<% @title_for_layout =  @category.present? ? @category.name : t('app.home') %>
<%= render 'layouts/generic_meta' %>

<% if action_name == "home" %>
<section class="pt15 pb15 bg-dark-grey noise-bg center">
  <h1 class="color-white h1 mb15"><%= @store.baseline.present? ? @store.baseline.html_safe : nil %></h1>
  <div class="container" style="<%= "height:500px;" if @products_for_slider.present? %>">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <% @products_for_slider.each_with_index do |product,x| %>
        <li data-target="#carousel-example-generic" data-slide-to="<%= x %>" class="<%= x == 0 ? "active" : nil %>"></li>
        <% end %>
      </ol>
      <div class="carousel-inner" role="listbox">
        <% @products_for_slider.each_with_index do |product,x| %>
        <div class="item <%= x == 0 ? "active" : nil %>">
          <%= link_to product_show_path(product.id) do %>
          <%= image_tag product.cover.url(:large), :class=>"img-responsive" %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
<% end %>


<div class="container pt35">
  <div class="row">
    <div class="col-md-3 col-sm-5 col-xs-12 pb50">
      <div id="home-sidebar" class="bg-white bAll border-grey mb5 pl5 pr5 pt5 pb5" data-spy="affix" data-offset-top="<%= action_name == 'home' ? '635' : '90' %>" data-offset-bottom="100">
        <h2 class="fs18 color-dark-grey medium mt5"><%= t('app.categories') %></h2>
        <hr class="mt10 mb15 bg-light-grey">
        <%= link_to t("app.home"), root_path, :class=>"fs13 medium inline-block ellipsis ml5" %>
        <div aria-multiselectable="true" class="ml5">
          <% @store.categories.each_with_index do |c,index| %>
          <a role="button" data-toggle="collapse" data-parent="#home-sidebar" href="#<%= "collpase_#{index}" %>" aria-expanded="true" aria-controls="<%= "collpase_#{index}" %>" class="fs13 medium inline-block ellipsis"><%= c.name %></a>
          <div id="<%= "collpase_#{index}" %>" class=" collapse <%= index != 0 ? nil : nil %>" role="tabpanel">
            <ul class="list-unstyled ml15">
              <% c.subcategories.sort_by { |sub| sub.name }.each do |sc| %>
              <li class="mb2"><%= link_to sc.name, category_show_path(sc.id), :class=>"fs11 color-link medium inline-block ellipsis" %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-9 pr30">
      <% @products_with_category.sort_by { |p| p.category.position }.group_by(&:category).each do |category,products_by_category| %>
      <% products_by_category.sort_by { |p| p.subcategory.name }.group_by(&:subcategory).each do |subcat,products| %>
      <section class="mb30">
        <h2 class="fs20 color-dark-grey medium inline-block uppercase"><%= "#{subcat.category.name} <span class='fs13'>/ #{subcat.name}</span>".html_safe %></h2>
        <hr class="mt5 mb20 bg-light-grey">
        <% products2 = action_name == "home" ?  products.shuffle![0..3] : products  %>
        <% products2.in_groups_of(2,false).each do |row_products| %>
        <div class="row products">
          <% row_products.each do |p| %>
          <div class="col-sm-6 product mb10">
            <%= render 'pages/card_product', :p => p %>
          </div>
          <% end %>
        </div>
        <% end %>
        <%= link_to "#{t('app.view_all')} (#{products.size})", category_show_path(subcat.id),:class=>"color-link lowercase" if products.size > 4 and action_name == "home"  %>
      </section>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

storeimmo/app/views/pages/product_show.html.erb
<% @title_for_layout = @brand = @product.name %>
<%= render 'layouts/generic_meta' %>

<% if @product.cover? %>
<section id="product-slider" class="noise-bg bg-dark-blue">
  <div class="centered-content flex pt25 pb25">
    <%= image_tag @product.cover.url(:large), :class=>"img-responsive inline-block" %>
  </div>
</section>
<% end %>

<header id="product-header">
  <div class="container">
    <div class="row wrapper">
      <div class="col-md-12">
        <div class="pull-left hidden-xs">
          <%= image_tag @product.logo.url(:medium),:class=>"img-responsive mt8" %>
        </div>
        <div class="titles pull-left pt10 pb15 pl15">
          <h1 class="fs18 color-dark-grey medium mt5"><%= @product.name %></h1>
          <p class="fs13 color-grey mt4 mb0 inline-block hidden-xs hidden-sm"><%= @product.baseline %></p>
          <h2 class="fs14 color-grey normal inline-block ml10"><%= @product.subcategory.present? ? link_to(@product.subcategory.name, category_show_path(@product.subcategory.id),:class=>"color-link medium") : link_to(t('app.others'), category_show_path,:class=>"color-link medium") %></h2>
        </div>
        <% main_pricing = @product.pricing  %>
        <% if main_pricing.present? %>
        <div class="pull-right hidden-xs">
          <div class="pt20 pb20 pl20 pr5 ml20 mt4 mb4 inline-block button-box">
            <span class="color-primary lh70 fs14">
              <%= main_pricing.price_from == 1 ? t('app.price_from') : nil %>
              <strong>
                <% if main_pricing.is_a_checkout? %>
                <% checkout = main_pricing.pricing_checkouts.last %>
                <%= (checkout.present? and main_pricing.checkout_unit.present?) ? "#{humanized_money_with_symbol checkout.price}#{main_pricing.checkout_unit.present? ? "#{main_pricing.checkout_unit.name}" : nil}" : nil %>
                <% end %>
                <% if  main_pricing.is_a_plan? %>
                <% plan = main_pricing.pricing_plan %>
                <%= "#{plan.present? ? "#{humanized_money_with_symbol plan.price_month_cents == 0 ? plan.price_year :  plan.price_month} #{plan.price_month_cents == 0 ? t('app.per_year') : t('app.per_month')}" : nil}" %>
                <% end %>
              </strong>
            </span>
          </div>
          <a href="#prices_container" class="btn btn-sm btn-primary"><%= t('app.pricings') %></a>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</header>
<div class="hide" id="fake-product-header"></div>


<div class="bg-white pt20">
  <%# Product description %>
  <div class="container">
    <div class="row">
      <section class="col-md-9 pr40">
        <% if  @product.summary.present? %>
        <div class="italic bg-light-grey mb25 pAll5 mt10">
          <div class="color-grey justify ml5 mr5"><%= @product.summary %></div>
        </div>
        <% end %>
        <div class="product-description justify">
          <%= @product.description.html_safe %>
        </div>
      </section>
      <section class="col-md-3 center">
        <% if @product.product_assets.present? %>
        <div class="bg-light-grey pt10 pb10">
          <ul id="image-gallery" class="list-inline mb0 ml0">
            <% @product.product_assets.each do |asset| %>
            <li class="pl2 pr2 br3 bAll border-grey"><a href="<%= asset.image.url(:medium) %>" class="zoombox zgallery1 bg-cover block" style="height:80px; width:80px;background-image:url(<%= asset.image.url(:small) %>);"></a></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <% if @product.video_url.present? %>
        <div class="svgContainer ratio56 mt5 mb20">
          <iframe width="560" height="315" src="<%= @product.video_url %>" frameborder="0" allowfullscreen></iframe>
        </div>
        <% end %>
      </section>
    </div>
  </div>

  <% if @product.is_printable && client_signed_in? %>
  <%# Print Management %>
  <div class="bg-dark-blue center mt20">
    <div class="container">
      <% if @print_call.present? %>
      <%# Show selected print %>
      <div class="h3 color-white mt10 mb10">Votre impression</div>
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <%= image_tag @print_call[:preview], :class=>"img-responsive" %>
        </div>
      </div>
      <% elsif @pdfs.present? %>
      <%# Select Print %>
      <div class="row mb30">
        <%= minimal_form_for :property ,:url => ENV['myprint_server'], :method => :get , :html=> {:id => "myprint_form", :class=>"form-inline"} do |f| %>
        <div class="col-sm-4">
          <div class="h4 color-white mt30 mb10"><%= t('app.print.step2') %></div>
          <div class="form-group">
            <%= f.input_field :pdf_id, :collection => @pdfs["pdfs"].map{|t| ["#{t["name"]} #{t["property_count"].present? ? "(#{t('app.properties', :count => t["property_count"])})" : nil}", t["id"], {'data-count'=> t["property_count"]} ]}, :class=>"form-control", :include_blank => false, :selected => @selected_pdf_id %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="h4 color-white mt30 mb10"><%= t('app.print.step3') %></div>
          <% if @pdfs["max_properites"].to_i >= 1 %>
          <% (1..@pdfs["max_properites"].to_i).each do |i| %>
          <div>
            <div class="form-group">
              <%= f.input_field :query, :placeholder =>"#{t('app.property')} ##{i}", :class=>"form-control typeaheadPrint #{i > @pdfs["pdfs"][0]["property_count"] ? "hide" : nil }", :data => {:i => i} %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="col-sm-4">
          <div class="h4 color-white mt30 mb10"><%= t('app.preview') %></div>
          <%= link_to t('app.preview'), "#", :class=>"btn btn-default" ,:id=>"linkPreview" %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>


  <%# Price %>
  <% if !@product.is_printable || (@product.is_printable && client_signed_in? ) %>
  <div class="bg-light-grey noise-bg pt20" id="prices_container">
    <div class="container">
      <% @product.pricings.where(:status => "active").group_by(&:is_a_plan?).each do |is_a_plan, grouped_pricings| %>
      <hr class="mt0 mb30">
      <% grouped_pricings.in_groups_of(3,false).each  do |row_pricings| %>
      <div class="row same-height-col">
        <% row_pricings.each do |pricing| %>
        <div class="col-sm-6 col-md-6 col-lg-4 mb80">
          <%= render "pages/price_card", :pricing => pricing, :path => cart_add_or_update_path %>
        </div>
        <% end %>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
  <% end %>

  <%# Linked products %>
  <% if @linked_products && @linked_products.size > 0 %>
  <div class="bg-white pt20">
    <div class="container">
      <h3 class="mb10 fs18 color-dark-grey medium inline-block"><%= t('app.linked_products') %></h3>
      <hr class="mt0 mb30">
      <div class="row products">
        <% @linked_products.each do |p| %>
        <div class="col-sm-4 product mb50">
          <%= render 'pages/card_product', :p => p %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

  <%# Signin printable %>
  <% if @product.is_printable && !client_signed_in? %>
  <div class="center pb40">
    <hr>
    <div class="h1 mt15"><%= t('app.print.warning_signin') %></div>
    <%= link_to t('app.signin'), new_client_session_path(:redirect_uri => request.url), :class=>"btn btn-primary mt10" %>
  </div>
  <% end %>
</div>


<%# Publipostage %>
<div class="modal fade z-index-10000" id="publipostageModal" tabindex="-1" role="dialog" aria-labelledby="publipostageModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="publipostageModal"><%= t('app.print.publipostage') %><small class="ml10"><%= t('app.print.step1') %></small></h4>
      </div>
      <div class="modal-body bg-light-grey">
        <%= minimal_form_for PostCanadaPublipostage.new , :url => publipostage_path, :remote => true, :html=>{:class=>"form-inline"} do |f| %>
        <div class="form-group">
          <%= f.input_field :zipcode, :placeholder =>"XXX",:class=>"form-control" %>
        </div>
        <%= f.submit :class =>"btn btn-default", :value =>t('app.find'),:wrapper_html => nil %>
        <% end %>
        <div id="RoadsResults"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('app.validate') %></button>
      </div>
    </div>
  </div>
</div>



<% if client_signed_in? %>
<%= javascript_tag do %>
window.clients_ads          = <%= raw @clients_ads.to_json %>;
window.myprint_server       = "<%= "#{ENV['myprint_server']}/#{I18n.locale}" %>"

<%# selected pdf id %>
window.myprint_pdf_id       = "<%= @selected_pdf_id %>"

<%# maximum number of properties %>
window.max_properties       = "<%= @pdfs.present? ? @pdfs["max_properites"] : 0 %>"

<%# selected property ids %>
window.myprint_uids         = []

<%# current number of properties %>
window.n                    = "<%= @n %>"

window.store_url            = "<%= request.url %>"
<% end %>
<% end %>

storeimmo/app/views/pages/stylesheet.css.erb
<%= @store.present? ? @store.theme : nil %>

storeimmo/app/views/pages/thanks.html.erb
<% @title_for_layout = @brand = t('app.home') %>
<%= render 'layouts/generic_meta' %>

<div class="layer flex-image">
  <div class="h1 flex-centered">
    <div class="new-line"></div>
    <div class="new-line"></div>

    <div class="text-center" style="width: 100%;">
      <p><%= t("thanks.title") %></p>
    </div>
    <%= link_to t("thanks.to_home"), root_path, :class => "btn btn-lg btn-custom-secondary mr15 ml15" %>
    <% if client_signed_in? %>
    <%= link_to t("thanks.to_services"), dashboard_path, :class => "btn btn-lg btn-custom-secondary mr15 ml15" %>
    <% end %>

    <div class="new-line"></div>
    <div class="new-line"></div>
  </div>
</div>