shareimmo_api/config/routes.rb
 require 'sidekiq/web'

 Rails.application.routes.draw do

  ##============================================================##
  ## API
  ##============================================================##
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      scope "centris" do
        match "brokers"  => "centris#brokers", :via => :post
      end
      scope "pagesimmo" do
        match "sync/:client_id"  => "pagesimmo#sync", :via => :get
      end
      scope "zipcodes" do
        match 'kijiji'            => 'zipcodes#kijiji_export', :via => :get
        match 'louer'             => 'zipcodes#louercom_export', :via => :get
        match 'centris/:id'       => 'zipcodes#centris_zipcode', :via => :get
      end
    end
  end



  root 'welcome#home'
  match 'dashboard' => 'welcome#dashboard', :via => [:get]

  ##============================================================##
  ##
  ##============================================================##
  match 'rake/poliris'  => 'rake#run_poliris', :via => [:get]


  ##============================================================##
  ## OAuth
  ##============================================================##
  get '/auth/:provider/callback', to: 'authentifications#create'
  get '/auth/failure', to: 'authentifications#fail'


  ##============================================================##
  ## Cette methode autorise l'url de sideKiq que pour les
  ## adminisatreur du site
  ##============================================================##
  authenticate :user, lambda { |u| u.check_role? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  ##============================================================##
  ## Centris
  ##============================================================##
  match 'dashboard/centris'                 => 'centris#ftp', :via => [:get]
  match 'dashboard/centris/banners'         => 'centris#banners', :via => [:get]
  match 'dashboard/centris/firms'           => 'centris#firms', :via => [:get]
  match 'dashboard/centris/offices'         => 'centris#offices', :via => [:get]
  match 'dashboard/centris/brokers'         => 'centris#brokers', :via => [:get]
  match 'dashboard/centris/inscriptions'    => 'centris#inscriptions', :via => [:get]
  match 'dashboard/centris/neighborhoods'   => 'centris#neighborhoods', :via => [:get]
  match 'dashboard/centris/cities'          => 'centris#cities', :via => [:get]
  match 'dashboard/centris/regions'         => 'centris#regions', :via => [:get]

  match 'dashboard/centris/offices/sync'    => 'centris#offices_sync', :via => [:get]
  match 'dashboard/centris/brokers/sync'    => 'centris#brokers_sync', :via => [:get]

  match 'dashboard/zipcodes'                => 'zipcodes#index', :via => [:get], :as => 'dashboard_zipcode'
  match 'dashboard/zipcode/:id'             => 'zipcodes#edit', :via => [:get], :as => 'dashboard_zipcode_edit'
  match 'dashboard/zipcode/:id/debug'       => 'zipcodes#debbuger', :via => [:get], :as => 'dashboard_debug_zipcode'


  resources :zipcodes, :only =>[:update]



  match 'dashboard/youtube'                => 'youtube#index', :via => [:get], :as => 'dashboard_youtube'

  resources :my_brokers





  ##============================================================##
  ## Magex
  ##============================================================##
  match 'dashboard/magex'                  => 'magex#ftp', :via => [:get]
  match 'dashboard/magex/accounts'         => 'magex#accounts', :via => [:get]
  match 'dashboard/magex/buildings'        => 'magex#buildings', :via => [:get]
  match 'dashboard/magex/units'            => 'magex#units', :via => [:get]
  match 'dashboard/magex/ftp/sync'         => 'magex#ftp_sync',via: [:get]




  devise_for :users, :skip => [:sessions], :controllers => { :registrations => :registrations }
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end


end

shareimmo_api/app/views/layouts/partials/_flash_messages.html.erb
<% flash.each do |name, msg| %>
<% unless msg.blank? %>

<% if msg.is_a?(String) %>
<div id="flashMessage">
  <div id="flashMessageContainer">
    <div class=" mb3 mt3 alert alert-<%= name == :notice ? "info" : "warning" %>">
      <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  </div>
</div>
<% end %>
<% end %>
<% end %>

shareimmo_api/app/views/layouts/partials/_footer.html.erb
<footer class="center">

</footer>

shareimmo_api/app/views/layouts/partials/_generic_meta.html.erb
<%#-- Default Meta -- %>
<% set_meta_tags :site => ENV['site_name'], :title => @title_for_layout ? @title_for_layout.html_safe : controller.action_name , :reverse => true %>
<% unless @description_for_layout.nil? %> <% set_meta_tags :description => @description_for_layout%> <% end %>
<% if @keywords_for_layout %> <% set_meta_tags :keywords => @keywords_for_layout %><% end %>
<% set_meta_tags :canonical => @canonical_for_layout ? @canonical_for_layout : request.original_url   %>

<% if @noindex_for_layout and @noindex_for_layout ==true %>
<% set_meta_tags :noindex => true %>
<% end %>

shareimmo_api/app/views/layouts/partials/_header.html.erb
<nav id="my--navbar" class="navbar navbar-default navbar-inverse mb0" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to dashboard_path,:class=>'navbar-brand' do%><%= ENV['site_name'] %><% end %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Monitoring<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li role="presentation" class="dropdown-header"><%="Mode : (#{Rails.env})" %></li>
            <li><%= link_to sidekiq_web_path, :target=>'blank' do %><i class="fa fa-weixin mr5"></i>Sidekiq<% end %></li>
            <li class="divider"></li>
            <li><%= link_to "/rails/mailers",:target=>"_blank" do %><i class="fa fa-paper-plane mr5"></i>Mails Tester<% end %></li>
          </ul>
        </li>
        <li <% if controller.controller_name == "centris"%> class="active"<% end %>><%= link_to dashboard_centris_path do %>Centris<% end %> </li>
        <li <% if controller.controller_name == "magex"%> class="active"<% end %>><%= link_to dashboard_magex_path do %>Magex<% end %> </li>
        <li <% if controller.controller_name == "zipcoodes"%> class="active"<% end %>><%= link_to dashboard_zipcode_path do %>ZipCode<% end %> </li>
        <li <% if controller.controller_name == "mybrokers"%> class="active"<% end %>><%= link_to my_brokers_path do %>My Brokers<% end %> </li>
        <li <% if controller.controller_name == "youtube"%> class="active"<% end %>><%= link_to dashboard_youtube_path do %>Youtube Vidéos<% end %> </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to(destroy_user_session_path, :method=>'delete') do %><i class="fa fa-sign-out mr5"></i>Déconexion<% end %></li>
        <% else %>
        <li><%= link_to new_user_session_path do %><i class="fa fa-sign-in mr5"></i>Connexion<% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>